FROM ubuntu:22.04

RUN apt update && apt install -y \
    openvpn \
    dante-server \
    iproute2 \
    iptables \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
COPY danted.conf /etc/danted.conf

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
